[package]
name = "myleveldb-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.7"
bumpalo = {version="3.7.0",features = ["collections"]}
integer-encoding = "3.0.2"
atomic = "0.5.0"